name: Credits workflow

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  sonar_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true

    - name: SonarQube Analysis
      uses: sonarsource/sonarcloud-action@v1
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-host-url: 'http://localhost:9000'

  build_and_run_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image for msvc-credits
      run: docker build -t msvc-credits ./msvc-credits

    - name: Run Docker containers
      run: |
        docker network create microservices_network || true
        docker run -d --network microservices_network --name msvc-credits -p 8081:8080 msvc-credits